# build environment
FROM node:12.13.1-alpine as build

# Set the current working directory inside the image
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# Copy package executable to the image
COPY package.json /app/package.json

# Build all the dependencies in preparation to go offline.
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# Copy the project source
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]